### ISSUE TITLE
Arduino Code

### ISSUE THREAD

**Issue by dyaa** [robertcedwards/httpFirebase#1]
Please i wanna know how the Arduino Code (.ino) will be.

I was searching for this everywhere and finally i found your repository.

**Comment by robertcedwards** [comment]
I've update the repo with the sketch…
Here's a link to the sketch for the post function:
https://github.com/robertcedwards/httpFirebase/blob/master/post.ino

**Comment by robertcedwards** [comment]
Let me know if you need help getting it setup…
We also we able to do this securely using an Arduino Yun, here's the repo for that:
https://github.com/robertcedwards/Arduino_Yun_CurlFire
